import heroIMG from './heroIMG.png'
import logoSVG from './logoSVG.svg'
import heroIMG2 from './heroIMG2.png'
import heroIMG3 from './heroIMG3.png'
import heroIMG4 from './heroIMG4.png'
import heroIMG5 from './heroIMG5.png'
import heroIMG6 from './heroIMG6.png'
import pattern from './pattern.png'
import aboutIMG from './aboutIMG.png'
import aboutIMG2 from './aboutIMG2.png'
import aboutIMG3 from './aboutIMG3.png'
import pcIcon from './PC.svg'
import xboxIcon from './XBOX.svg'
import psIcon from './PS.svg'
import genresIMG from './genres.png' 
import shooterIMG from './shooter.png'
import rpgIMG from './rpg.png'
import adventureIMG from './adventure.png'
import strategyIMG from './strategy.png'
import actionIMG from './action.png'
import indieIMG from './indie.png'

export { heroIMG, actionIMG, strategyIMG, indieIMG, adventureIMG, rpgIMG, shooterIMG, logoSVG, heroIMG2, heroIMG3, heroIMG4, heroIMG6, heroIMG5, pattern, aboutIMG, aboutIMG2, aboutIMG3, pcIcon, psIcon, xboxIcon, genresIMG,  } 